### ISSUE TITLE
[Feature Request] Context Menu Hotkey - Mouse Right Click

### ISSUE THREAD

**Issue by FelipeRearden** [kzhovn/obsidian-customizable-menu#1]
Hello @kzhovn !!!

First of all, thank you very much for this plug-in! I's a great idea!

**My FR is very simple: A hotkey to the mouse right click (`Open Context Menu`)**

### Why I'm requesting this ?

Unfortunately, MacOS don't have dedicated keyboard key to do mouse right click. If you search on Google it is not very simple to do in MacOS :(
- Windows have a dedicated key
- Linux have `Shift + F10`

This way, I really need a hotkey to access the `Context Menu` in Obsidian :)

Thanks for reading this!

Have a great day!

**Comment by kzhovn** [comment]
I don't think I'm going to be able to implement this soon, the API doesn't seem to support doing it the easy way and working around that will be quite difficult. Closing for now, I'll reopen it if I decide to work on it.

**Comment by FelipeRearden** [comment]
Thanks for your reply and your help.

I hope in the future Obsidian API brings new features that makes this easy to do. 

Thanks for you help.
