### ISSUE TITLE
Right Menu Click on iPad Pro

### ISSUE THREAD

**Issue by pixelinkmedia** [kzhovn/obsidian-customizable-menu#10]
Where do I find the custom menu popup on my iPad Pro?

Plugin Works great on Win 10 PC, but not on iPad Pro (OS 15 - Obsid ver 1.05

Thanks

**Comment by kzhovn** [comment]
To be honest I have no idea how to activate the context menu on mobile and can't test on iPads. Not going to try fix this for now.
