### ISSUE TITLE
Feature Request: Allow removal of items from right click menu

### ISSUE THREAD

**Issue by brimwats1** [kzhovn/obsidian-customizable-menu#2]
My right click menu is totally overwhelming, I'd like to clean it up but there's currently no way to.

**Comment by Quorafind** [comment]
The same

**Comment by kzhovn** [comment]
Do you want to remove plugin-generated menu items or built in Obsidian commands? (I currently suspect the API doesn't really allow for removing default Obsidian commands, though I'm trying to figure it out, but plugin commands might be easier.)

**Comment by brimwats** [comment]
either/or but mostly other plugin commands

**Comment by GitMurf** [comment]
I agree as well on this! Would be so nice to be able to fully customize the menu to remove the noise that I never use :-)

**Comment by brimwats** [comment]
thanks @claremacrae — i came here to point that out—can you use the same code so the right click menu can be edited too @kzhovn ?

**Comment by kzhovn** [comment]
I can't use the same code because phibr0 is targeting aria-label via CSS (the text that shows up in a tooltip when you hover). Menu items don't have an aria-label. I've got a couple ideas for how to do this, we'll see if any of them pan out.

**Comment by kzhovn** [comment]
Quite a few months later, https://github.com/kzhovn/obsidian-customizable-menu/releases/tag/2.2.0 implements this. Let me know if there are any issues!

**Comment by Quorafind** [comment]
@kzhovn Could you add some example to the README or tell me what I need to add for removing items?
