### ISSUE TITLE
What is the right click menu?

### ISSUE THREAD

**Issue by MatteCrystal** [kzhovn/obsidian-customizable-menu#4]
I have no idea what right-click menu this plugin is referring too. I've tried right-clicking just about everything I can think of in obsidian and don't see any of my personalized options. 

Please update the readme to make this more clear and consider adding images.

-- 
Update: Looks like it only works when clicking a note in edit mode. This should be mentioned in the description.

**Comment by kzhovn** [comment]
Closed in favor of #5. ("Soon" clearly did not materialize, sorry! I'm hoping that I'll have time when my semester ends to come back to my Obsidian plugins, but I've learned my lesson about promising times).
